CREATE TABLE "published_properties" (
	"id" serial PRIMARY KEY NOT NULL,
	"original_property_id" integer NOT NULL,
	"user_id" uuid NOT NULL,
	"slug" text NOT NULL,
	"unique_id" text NOT NULL,
	"property_type" text NOT NULL,
	"property_title" text NOT NULL,
	"property_description" text,
	"state" text NOT NULL,
	"district" text NOT NULL,
	"city" text NOT NULL,
	"locality" text NOT NULL,
	"pincode" text NOT NULL,
	"latitude" text,
	"longitude" text,
	"total_area" text NOT NULL,
	"area_unit" text NOT NULL,
	"property_facing" text NOT NULL,
	"open_sides" text NOT NULL,
	"east_road_width" text,
	"west_road_width" text,
	"north_road_width" text,
	"south_road_width" text,
	"bedrooms" text,
	"bathrooms" text,
	"floors" text,
	"floor_number" text,
	"construction_status" text,
	"land_type" text,
	"boundary_wall" text,
	"amenities" jsonb,
	"selling_price" text NOT NULL,
	"price_type" text NOT NULL,
	"negotiable" text NOT NULL,
	"circle_rate" text,
	"published_photos" text[],
	"is_live" boolean DEFAULT false,
	"published_at" timestamp,
	"published_by" uuid,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "published_properties_slug_unique" UNIQUE("slug"),
	CONSTRAINT "published_properties_unique_id_unique" UNIQUE("unique_id")
);
--> statement-breakpoint
ALTER TABLE "published_properties" ADD CONSTRAINT "published_properties_original_property_id_properties_id_fk" FOREIGN KEY ("original_property_id") REFERENCES "public"."properties"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "published_properties" ADD CONSTRAINT "published_properties_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "published_properties" ADD CONSTRAINT "published_properties_published_by_users_id_fk" FOREIGN KEY ("published_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;